version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: python graphstore/run_server.py
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
