# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 14:54
from __future__ import unicode_literals

from django.db import migrations


def create_nodetypes(apps, schema_editor):
    NodeType = apps.get_model('graph', 'NodeType')
    for nodetype in ['class', 'individual', 'event', 'tuple']:
        NodeType(name=nodetype).save()


def delete_nodetypes(apps, schema_editor):
    NodeType = apps.get_model('graph', 'NodeType')
    for nodetype in ['class', 'individual', 'event', 'tuple']:
        NodeType(name=nodetype).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_nodetypes, delete_nodetypes)
    ]
