# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20160728_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('uuid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.NodeType')),
            ],
        ),
    ]
